[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-notification-service"
version = "0.1.0"
description = "Scalable notification microservice"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.mypy]
mypy_path = ["src"]
explicit_package_bases = true